BUILD="./release-build.sh"

all:
	@sh $(BUILD)

s sqlalert b bin:
	@sh $(BUILD) sqlalert

r rule rules:
	@sh $(BUILD) 'rules'

clean cleanup clear cl:
	@sh $(BUILD) clean

co checkout check:
	@sh ./release-checkout.sh
	
