// Rule script functions.
//
// Copyright (C) 2017 Yun Li Lai, Inc. All Rights Reserved.
// Written by: ZHANG Li Dan.
package funcs

import (
	"core/script"
	"sync"
)

// All builtin function for rule.
var g_functions_once sync.Once
var g_functions map[string]script.Func

func init_functions() {
	g_functions = map[string]script.Func{
		"agg_avg":            aggAvg,
		"agg_items":          aggItems,
		"agg_items_max":      aggItemsMax,
		"agg2_items_max":     agg2ItemsMax,
		"agg3_items_max":     agg3ItemsMax,
		"agg4_items_max":     agg4ItemsMax,
		"agg_max":            aggMax,
		"agg_median":         aggMedian,
		"agg_min":            aggMin,
		"agg_percentile":     aggPercentile,
		"agg_stdev":          aggStdev,
		"agg_sum":            aggSum,
		"agg_values":         aggValues,
		"agg_variance":       aggVariance,
		"alert":              alertAlert,
		"alert_es":           alertElastic,
		"alert_email":        alertEmail,
		"append":             miscAppend,
		"append_first":       miscAppendFirst,
		"append_list":        miscAppendList,
		"avg":                statAvg,
		"call":               miscCall,
		"call_builtin":       miscCallBuiltin,
		"call_list":          miscCallList,
		"check_datetime":     miscCheckDateTime,
		"copy":               miscCopy,
		"delete":             miscDelete,
		"dict_get":           miscDictGet,
		"exec_file":          miscExecFile,
		"exec_async":         miscExecAsync,
		"exit":               miscExit,
		"error":              miscError,
		"fmt_bytes":          fmtBytes,
		"fmt_bits":           fmtBits,
		"fmt_float":          fmtFloat,
		"fmt_int":            fmtInt,
		"fmt_pct":            fmtPercentage,
		"fmt_percentage":     fmtPercentage,
		"fmt_str":            fmtStr,
		"fmt_time":           fmtTime,
		"get_context":        miscGetContex,
		"get_ctx":            miscGetContex,
		"get_global":         miscGetGlobal,
		"get_session":        miscGetSession,
		"has_func":           miscHasFunc,
		"has_prefix":         miscHasPrefix,
		"has_suffix":         miscHasSuffix,
		"is_dict":            miscIsDict,
		"is_empty":           miscIsEmpty,
		"is_float":           miscIsFloat,
		"is_func":            miscIsFunc,
		"is_int":             miscIsInt,
		"is_list":            miscIsList,
		"is_null":            miscIsNull,
		"is_num":             miscIsNum,
		"is_str":             miscIsStr,
		"is_strlist":         miscIsStrList,
		"ip_in":              miscIpIn,
		"ip_map":             miscIPMap,
		"item_filter":        itemFilter,
		"item_max":           itemMax,
		"item_median":        itemMedian,
		"item_min":           itemMin,
		"item_percentile":    itemPercentile,
		"item_set":           itemSet,
		"item_values":        itemValues,
		"join":               miscJoin,
		"join_values":        miscJoinValues,
		"keys":               miscKeys,
		"len":                miscLen,
		"level_desc":         levelDesc,
		"level_desc_hl":      levelDescHighlight,
		"level_name":         levelName,
		"level_name_hl":      levelNameHighlight,
		"level_name_desc":    levelNameDesc,
		"level_name_desc_hl": levelNameDescHighlight,
		"list":               miscList,
		"list_empty":         miscListEmpty,
		"list_not_empty":     miscListNotEmpty,
		"list_to_dict":       miscListToDict,
		"load_json":          miscLoadJson,
		"max":                statMax,
		"median":             statMedian,
		"min":                statMin,
		"multi_call":         miscMultiCall,
		"multi_exec":         miscMultiExec,
		"multi_query":        miscMultiQuery,
		"now":                miscNow,
		"percentile":         statPercentile,
		"pprint":             miscPPrint,
		"print":              miscPrint,
		"print_context":      miscPrintContext,
		"print_ctx":          miscPrintContext,
		"print_list":         miscPrintList,
		"query":              elasticQuery,
		"query_avgby_num":    elasticQueryAvgbyNum,
		"query_avgby_field":  elasticQueryAvgbyField,
		"remove_first":       miscRemoveFirst,
		"remove_last":        miscRemoveLast,
		"reverse":            miscReverse,
		"run":                miscRun,
		"set_global":         miscSetGlobal,
		"set_local":          miscSetLocal,
		"set_session":        miscSetSession,
		"slice":              miscListSlice,
		"sort":               miscSort,
		"sort_r":             miscSortReverse,
		"split":              miscSplit,
		"sql_make":           sqlMake,
		"stdev":              statStdev,
		"str":                miscStr,
		"sum":                statSum,
		"sys_now":            miscSysNow,
		"sys_time":           miscSysTime,
		"time":               miscTime,
		"throttle_check":     throttleCheck,
		"trim":               miscTrim,
		"values":             miscValues,
		"variance":           statVariance,
		"v_max":              valueMax,
		"v_min":              valueMin,
		"value_max":          valueMax,
		"value_min":          valueMin,
		"value_map":          valueMap,
		"value_median":       valueMedian,
		"value_avg":          valueAvg,
		"value_sum":          valueSum,
		"value_variance":     valueVariance,
		"value_stdev":        valueStdev,
		"value_percentile":   valuePercentile,
	}
}

// FuncDict() - Returns function dict.
func FuncDict() map[string]script.Func {
	g_functions_once.Do(init_functions)
	return g_functions
}
